# Generated by Django 4.1.7 on 2023-03-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0005_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(),
        ),
    ]
